### ISSUE TITLE
返回的数据啥编码啊?

### ISSUE THREAD

**Issue by wingfordream** [TencentYouTu/python_sdk#2]
返回的tag_name对应的值:u'\xe5\xae\xa0\xe7\x89\xa9',我用utf8解码都是乱码啊!

ret = youtu.imagetag("1.jpg", data_type = 0, seq = '')
print ret["tags"][0]["tag_name"].encode('utf8')

**Comment by wingfordream** [comment]
好吧！ISO-8859-1编码~！~~

**Comment by zhtsky** [comment]
@wingfordream 那应该怎么转中文呢 在python3中
